name: Android Java 25 CI & CodeQL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codeql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set up Oracle JDK 25
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 25

      # 1️⃣ Manual Gradle build before CodeQL
      - name: Build project with Gradle
        run: ./gradlew assemble

      # 2️⃣ Initialize CodeQL in manual build mode
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java
          # key setting:
          build: manual

      # 3️⃣ Run CodeQL analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2